import React,{useState,useEffect} from 'react';
import type {FormEvent} from 'react';
import {useApp} from '../lib/context';
import {api,post,signIn} from '../lib/api';
import {isStaffUser} from '../lib/auth';
import {useData} from '../lib/useData';
import {useMapData} from '../lib/useMapData';
import {saveDraft,removeDraft,newDraft} from '../lib/drafts';
import type {Dashboard,Collection,CaseReport,Advisory,Prediction,Evidence,Draft,Message,User} from '../lib/types';
import {Button,Card,Notice,Empty,Loading,ErrorBox,Field,PageHead,Icon,Hero,Badge,State,PredictionState,ImageView,date,nice,categoryIcon} from '../components/ui';
import {ReportList,AdvisoryCard} from '../components/ReportCards';
import {MapPanel} from '../components/MapPanel';

export function Welcome(){const {nav}=useApp();return <div className="welcome-page"><div className="welcome-art"><img src="/assets/elephant.jpg" alt="Illustrated elephant in a green landscape"/><span>People. Wildlife. Wetlands.<br/>Safer, together.</span></div><Badge>WILDLIFE FIRST</Badge><h1>A clearer path from sighting to response.</h1><p>Report what you see. Keep evidence private. Follow a human review and stay informed.</p><div className="quick-grid"><span><Icon name="camera"/>Report</span><span><Icon name="check"/>Review</span><span><Icon name="bell"/>Stay informed</span></div><Button variant="wide" onClick={()=>nav('signin')} icon="arrow">Get started</Button><Button variant="ghost wide" onClick={()=>nav('nearby')} icon="map">See what's near you — no sign-in needed</Button><Button variant="ghost wide" onClick={()=>nav('help')}>How EcoGuard works</Button><small>No automatic public alert from an AI suggestion. Not an emergency-dispatch service.</small></div>;}

export function SignIn(){const {setUser,nav,config,notify}=useApp();const [joining,setJoining]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const u=await signIn(email,password,joining?name:undefined);setUser(u);nav(isStaffUser(u)?'dashboard':'home',isStaffUser(u)?'workspace':'community');notify(joining?'Your account is ready.':'Welcome back.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><PageHead label="WELCOME TO ECOGUARD" title={joining?'Join your community':'Good to see you again.'} subtitle="Sign in to report, review and follow up."/><div className="tabrow"><button className={!joining?'tab active':'tab'} onClick={()=>setJoining(false)}>Sign in</button><button className={joining?'tab active':'tab'} onClick={()=>setJoining(true)}>Create account</button></div><form className="stack" onSubmit={submit}>{joining&&<Field label="Your name"><input value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={100} autoComplete="name"/></Field>}<Field label="Email address"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" placeholder="name@example.org"/></Field><Field label="Password" hint={joining?'At least 12 characters.':'Use the password set by you or your administrator.'}><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={joining?12:1} autoComplete={joining?'new-password':'current-password'}/></Field>{error&&<ErrorBox message={error}/>}<Button type="submit" disabled={busy} variant="wide">{busy?'Signing in…':joining?'Create community account':'Sign in securely'}</Button></form><Notice><Icon name="lock" size={16}/> New accounts can submit their own reports. Review and publishing permissions are assigned separately.</Notice><p className="staff-gate-alt">EcoGuard staff: <a href="#/staff/login">use the staff sign-in</a>. Accounts without a staff role are not admitted there.</p><small>Account recovery is administrator-assisted in this release; no fake recovery email is sent.</small></>;
}

export function Home(){const {nav,startDraft,user}=useApp();const dashboard=useData<Dashboard>('/dashboard',20000),alerts=useData<Collection<Advisory>>('/advisories',20000);
 return <><PageHead label="COMMUNITY HOME" title={`Hello, ${user?.name.split(' ')[0]||'neighbour'}.`} subtitle="A small observation can be the start of useful action."/><Card className="report-cta"><div><h3>Report a wildlife sighting</h3><p>Attach a photo or describe what you saw. Every report is read by a human reviewer before anything is published.</p></div><Button icon="paw" onClick={()=>{startDraft('wildlife');nav('upload','community');}}>Start a wildlife report</Button></Card><Hero mobile onNavigate={p=>{if(p==='upload'||p==='wetland')startDraft(p==='upload'?'wildlife':'wetland');if(p==='flood'){startDraft('flood');nav('floodreport','community');return}nav(p);}}/><div className="quick-grid">{[['map','map','Community map'],['nearby','map','Near me'],['myreports','file','My reports'],['alerts','bell','Advisories']].map(([p,i,t])=><button key={p} onClick={()=>nav(p)}><Icon name={i}/>{t}</button>)}</div><div className="row between"><h2>Reviewed updates</h2><button className="link" onClick={()=>nav('alerts')}>View all</button></div>{alerts.loading?<Loading/>:alerts.error?<ErrorBox message={alerts.error} retry={alerts.reload}/>:alerts.data?.items.length?<AdvisoryCard item={alerts.data.items[0]} onOpen={()=>nav('alertdetail','community',alerts.data!.items[0].id)}/>:<Empty title="No active advisories"/>}<Card><div className="row between"><h3>Your contributions</h3><Badge>{dashboard.data?.counts.total||0} reports</Badge></div><p>Follow your case from submission to review and response.</p><Button variant="ghost wide" onClick={()=>nav('myreports')}>View your report history</Button></Card><div className="grid2"><Button variant="ghost" onClick={()=>{startDraft('wetland');nav('wetland');}}>Wetland report</Button><Button variant="ghost" onClick={()=>{startDraft('flood');nav('floodreport');}}>Flood observation</Button></div></>;
}

export function Upload(){const {draft,setDraft,user,nav,notify}=useApp();const [preview,setPreview]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(!draft?.image)return;const u=URL.createObjectURL(draft.image);setPreview(u);return()=>URL.revokeObjectURL(u);},[draft?.image]);
 function choose(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG or WebP image.');return;}if(file.size>10*1024*1024){setError('Choose an image under 10 MB.');return;}const d={...(draft||newDraft(user!.id)),image:file,image_name:file.name,evidence:undefined,prediction:undefined};setDraft(d);saveDraft(d).catch(()=>notify('Device storage is unavailable. Keep this page open.'));setError('');}
 return <><PageHead label="WILDLIFE REPORT • 1 OF 4" title="Start with an image." subtitle="Use an existing photo or take one only from a safe distance."/><label className="uploadbox"><Icon name="camera" size={42}/><strong>{draft?.image_name||'Add wildlife evidence'}</strong><span>JPG, PNG or WebP • up to 10 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/></label>{preview&&<ImageView url={preview} label="On this device • not yet uploaded"/>}{error&&<ErrorBox message={error}/>}<Notice><strong>Your image stays private.</strong> Metadata is stripped when uploaded. Only you and authorised case staff can view the evidence.</Notice><Button disabled={!draft?.image&&!draft?.evidence} variant="wide" onClick={()=>nav('identify')}>Continue to image review <Icon name="arrow"/></Button><Button variant="ghost wide" onClick={()=>nav('wildlife')}>Report a sighting without a photo</Button><small>Never approach an animal to obtain better evidence. A photo is not required to report.</small></>;
}

export function Identify(){const {draft,setDraft,nav,notify,config}=useApp();const [busy,setBusy]=useState(false),[error,setError]=useState('');const [permitted,setPermitted]=useState(false);
 const result=useData<Prediction>(draft?.prediction?.id?`/predictions/${draft.prediction.id}`:null,draft?.prediction?.state==='queued'?2000:0);
 useEffect(()=>{if(result.data&&draft&&JSON.stringify(result.data)!==JSON.stringify(draft.prediction))setDraft({...draft,prediction:result.data});},[result.data]);
 async function analyse(){if(!draft||!permitted)return;setBusy(true);setError('');try{let evidence=draft.evidence;if(!evidence&&draft.image){const f=new FormData();f.append('file',draft.image,draft.image_name||'evidence.jpg');evidence=await api<Evidence>('/evidence',{method:'POST',body:f});}if(!evidence)throw Error('Add an image first.');setDraft({...draft,evidence});const prediction=await post<Prediction>('/predictions',{evidence_id:evidence.id});const next={...draft,evidence,prediction};setDraft(next);await saveDraft(next);notify('Image-assistance request recorded. Human review is still required.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const p=result.data||draft?.prediction;
  const pending=busy||p?.state==='queued'||p?.state==='processing';
  return <><PageHead label="WILDLIFE REPORT • 2 OF 4" title="Review, never assume." subtitle="An image suggestion is not a verified incident."/>{draft?.evidence&&<ImageView url={draft.evidence.url} label="Private uploaded evidence"/>}<Card><div className="row between"><h3>Image assistance</h3><PredictionState state={p?.state||'not_requested'}/></div>{p?.species?<><h2>{p.species}</h2><p>Model confidence: {p.confidence===null?'Not available':`${Math.round(p.confidence*100)}%`}. This is a candidate, not confirmation.</p><small>SpeciesNet whole-image classifier. A human reviewer confirms any species before publication.</small></>:<p>{p?.explanation||'Request a candidate identity or continue with your own observation.'}</p>}{config?.image_assistance==='not_configured'&&<Notice tone="amber">No trained wildlife model is configured. Requests return “unavailable”, not an invented species or confidence.</Notice>}{config?.image_assistance==='degraded'&&p?.state==='unavailable'&&<Notice tone="amber">Image assistance is not working right now. Record your own observation; you can retry later.</Notice>}<label className="checkrow"><input type="checkbox" checked={permitted} onChange={e=>setPermitted(e.target.checked)}/>I permit private upload and processing of this image for the report.</label><Button variant="ghost wide" disabled={pending||!permitted||(!draft?.image&&!draft?.evidence)} onClick={analyse}>{busy?'Uploading…':pending?'Waiting for the model…':p?.state?'Request again':'Request image assistance'}</Button></Card>{error&&<ErrorBox message={error}/>}<Field label="Observed or suggested species" hint="You may leave this as Unknown animal."><input value={draft?.species||''} onChange={e=>draft&&setDraft({...draft,species:e.target.value})}/></Field>{p?.species&&<Button variant="ghost" onClick={()=>draft&&setDraft({...draft,species:p.species!})}>Use candidate as a suggestion</Button>}<Button variant="wide" onClick={()=>nav('wildlife')}>Add the sighting details <Icon name="arrow"/></Button></>;
}

export function ReportForm({category='wildlife'}:{category?:'wildlife'|'wetland'|'flood'}){const {draft,setDraft,user,areas,nav,notify}=useApp();const d=draft||newDraft(user!.id,category);const [error,setError]=useState('');
 useEffect(()=>{if(!draft)setDraft(d);},[]);
 const update=(changes:Partial<Draft>)=>setDraft({...d,...changes,category});
 async function next(e:FormEvent){e.preventDefault();const next={...d,category};try{await saveDraft(next);setDraft(next);nav('review');}catch{setError('This browser could not save the draft. Free some device storage and retry.');}}
 const title=category==='wildlife'?'What did you observe?':category==='wetland'?'Report a wetland concern.':'Share a water observation.';
 return <><PageHead label={`${category.toUpperCase()} REPORT • DETAILS`} title={title} subtitle="Describe what you observed, not assumptions about the cause."/><form className="stack" onSubmit={next}><Field label="Report title"><input required minLength={5} maxLength={160} value={d.title} onChange={e=>update({title:e.target.value})} placeholder={category==='wildlife'?'Possible elephant near a field':'Describe the observation briefly'}/></Field>{category==='wildlife'&&<Field label="Species (when known)"><input value={d.species} maxLength={100} onChange={e=>update({species:e.target.value})}/></Field>}<Field label="Community / approximate area"><select required value={d.area_id} onChange={e=>update({area_id:e.target.value})}><option value="">Choose an area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Observation time"><input type="datetime-local" required value={toLocal(d.observed_at)} onChange={e=>{if(e.target.value)update({observed_at:new Date(e.target.value).toISOString()});}}/></Field><Field label="Observation and context" hint="Do not include personal phone numbers or precise wildlife coordinates in this text."><textarea rows={4} required minLength={10} maxLength={5000} value={d.description} onChange={e=>update({description:e.target.value})} placeholder="What happened? What could you see? What remains uncertain?"/></Field><details><summary>Optional private location</summary><label className="checkrow"><input type="checkbox" checked={d.share_location} onChange={e=>update({share_location:e.target.checked,...(!e.target.checked?{latitude:'',longitude:''}:{})})}/>Share a precise position with authorised case staff only.</label>{d.share_location&&<><div className="grid2"><Field label="Latitude"><input type="number" step="any" min={-90} max={90} value={d.latitude} onChange={e=>update({latitude:e.target.value})}/></Field><Field label="Longitude"><input type="number" step="any" min={-180} max={180} value={d.longitude} onChange={e=>update({longitude:e.target.value})}/></Field></div><Button variant="ghost small" onClick={()=>{if(!navigator.geolocation){notify('Geolocation is unavailable. Enter the position manually or omit it.');return;}navigator.geolocation.getCurrentPosition(p=>update({latitude:String(p.coords.latitude),longitude:String(p.coords.longitude)}),()=>notify('Location access was not granted. You may leave the precise location blank.'),{timeout:10000});}}>Use current position</Button></>}</details>{error&&<ErrorBox message={error}/>}<Button type="submit" variant="wide">Review privacy & submit <Icon name="arrow"/></Button><Button variant="ghost wide" onClick={async()=>{try{await saveDraft(d);notify('Draft saved on this device. It has not been submitted.');}catch{notify('Could not save the draft to device storage.');}}}>Save on this device</Button></form><Notice>No network is needed to save this form locally. Uploads and submission require connectivity.</Notice></>;
}
function toLocal(iso:string){const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}

export function ReviewSubmit(){const {draft,setDraft,areas,nav,changed,notify}=useApp();const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(){if(!draft)return;setBusy(true);setError('');let d={...draft};try{
  if(!d.consent)throw Error('Please give permission to transmit the report.');
  if(d.image&&!d.evidence){const f=new FormData();f.append('file',d.image,d.image_name||'evidence.jpg');d.evidence=await api<Evidence>('/evidence',{method:'POST',body:f});setDraft(d);await saveDraft(d);}
  const body={client_id:d.client_id,category:d.category,title:d.title,description:d.description,species:d.species,area_id:d.area_id,observed_at:d.observed_at,latitude:d.latitude?Number(d.latitude):null,longitude:d.longitude?Number(d.longitude):null,share_location:d.share_location,consent:d.consent,evidence_ids:d.evidence?[d.evidence.id]:[]};
  let report:CaseReport;
  if(d.server_id){report=await api<CaseReport>(`/reports/${d.server_id}`);if(report.state==='draft'||report.state==='needs_evidence')report=await api<CaseReport>(`/reports/${d.server_id}`,{method:'PUT',body:JSON.stringify({...body,version:report.version})});}
  else report=await post<CaseReport>('/reports',body);
  d={...d,server_id:report.id,server_version:report.version};setDraft(d);await saveDraft(d);
  const final=await post<CaseReport>(`/reports/${report.id}/submit`,{version:report.version});
  setDraft({...d,submitted:true,server_version:final.version});await removeDraft(d.owner);changed();nav('success','community',final.id);notify('Submitted for human review. No public advisory has been published.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!draft)return <Empty title="No draft to review" action={<Button onClick={()=>nav('upload')}>Start a report</Button>}/>;
 return <><PageHead label="FINAL CHECK" title="Your report. Your choices." subtitle="Review the details before sending them to EcoGuard."/><Card><Badge>{nice(draft.category)}</Badge><h2>{draft.title||'Untitled observation'}</h2><p>{draft.description||'Details are missing.'}</p><div className="line"/><dl><dt>Area</dt><dd>{areas.find(a=>a.id===draft.area_id)?.name||'Not selected'}</dd><dt>Observed</dt><dd>{date(draft.observed_at)}</dd><dt>Image</dt><dd>{draft.image_name||draft.evidence?.filename||'No image attached'}</dd><dt>Precise location</dt><dd>{draft.share_location&&draft.latitude?'Private to case staff':'Not shared'}</dd></dl><Button variant="ghost small" onClick={()=>nav(draft.category==='wildlife'?'wildlife':draft.category==='wetland'?'wetland':'floodreport')}>Edit details</Button></Card><Notice><Icon name="lock" size={16}/> Images and exact coordinates do not appear on the community map. A separate publisher reviews any public advisory.</Notice><label className="checkrow consent"><input type="checkbox" checked={draft.consent} onChange={e=>setDraft({...draft,consent:e.target.checked})}/>I agree to send this report and any attached evidence for authorised review and case follow-up.</label>{error&&<ErrorBox message={error}/>}<Button variant="wide" disabled={busy||!draft.consent} onClick={submit}>{busy?'Sending report…':'Submit for human review'}</Button><small>Repeated attempts use the same draft identifier to avoid duplicate reports. A submission is not an emergency request.</small></>;
}

export function Success(){const {id,draft,nav}=useApp();const r=useData<CaseReport>(id?`/reports/${id}`:draft?.server_id?`/reports/${draft.server_id}`:null);return <><div className="success-icon"><Icon name="check" size={50}/></div><PageHead title="Your observation is on its way." subtitle="An authorised reviewer will inspect the evidence. This is not yet a public alert."/>{r.data&&<Card><State state={r.data.state}/><h2>{r.data.code}</h2><p>{r.data.title}</p><small>{date(r.data.created_at)}</small></Card>}<Button variant="wide" onClick={()=>nav('detail','community',id||draft?.server_id)}>Track this report</Button><Button variant="ghost wide" onClick={()=>nav('home')}>Return to home</Button></>;}

export function Alerts({flood=false}:{flood?:boolean}){const {nav,startDraft}=useApp();const [filter,setFilter]=useState(flood?'flood':'');const d=useData<Collection<Advisory>>('/advisories'+(filter?'?category='+filter:''),15000);
 return <><PageHead label="HUMAN-REVIEWED INFORMATION" title={flood?'Flood information':'Advisories & updates'} subtitle="Check the source, review state and expiry before acting." action={<Button variant="ghost small" onClick={d.reload} icon="bell">Refresh</Button>}/>{flood&&<><ImageView fallback="flood"/><Notice tone="blue">This page shares reviewed community information. No live sensor or forecasting service is connected.</Notice><Button onClick={()=>{startDraft('flood');nav('floodreport');}} icon="plus">Report a water observation</Button></>}{!flood&&<div className="tabrow">{[['','All'],['wildlife','Wildlife'],['wetland','Wetlands'],['flood','Floods']].map(([v,l])=><button className={'tab '+(filter===v?'active':'')} key={v} onClick={()=>setFilter(v)}>{l}</button>)}</div>}{d.loading&&!d.data?<Loading/>:d.error?<ErrorBox message={d.error} retry={d.reload}/>:<div className="stack">{d.data?.items.map(a=><AdvisoryCard key={a.id} item={a} onOpen={()=>nav('alertdetail','community',a.id)}/>)}{!d.data?.items.length&&<Empty title="No active advisories in this category"/>}</div>}</>;
}
export function AlertDetail(){const {id,nav}=useApp();const d=useData<Advisory>(id?`/advisories/${id}`:null);useEffect(()=>{if(d.data&&d.data.state==='published')post(`/advisories/${id}/read`,{}).catch(()=>{});},[d.data?.id]);if(!id)return <Empty title="Choose an advisory" action={<Button onClick={()=>nav('alerts')}>Browse advisories</Button>}/>;if(d.loading)return <Loading/>;if(d.error)return <ErrorBox message={d.error}/>;const a=d.data!;return <><PageHead label={a.category.toUpperCase()} title={a.title}/><State state={a.state}/>{a.state==='retracted'&&<Notice tone="red">Retracted: {a.retraction_reason}. Do not use this advisory as current guidance.</Notice>}<Card><p className="advisory-body">{a.body}</p><div className="line"/><dl><dt>Approximate area</dt><dd>{a.area_name}</dd><dt>Source</dt><dd>{a.source}</dd><dt>Published</dt><dd>{date(a.published_at)}</dd><dt>Expires</dt><dd>{date(a.expires_at)}</dd></dl></Card><Notice>Stay at a safe distance and follow guidance from the appropriate responders. EcoGuard does not dispatch emergency services.</Notice><Button variant="ghost" onClick={()=>nav('map')}>View community map</Button></>;}

export function MyReports(){const {nav}=useApp();const [filter,setFilter]=useState('');const d=useData<Collection<CaseReport>>('/reports?mine=true&page_size=100'+(filter?'&state='+filter:''),20000);return <><PageHead title="Your reporting journey" subtitle="Private drafts, evidence requests and completed case records."/><Field label="Filter by status"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All reports</option>{['draft','submitted','under_review','needs_evidence','verified','rejected','closed'].map(s=><option key={s} value={s}>{nice(s)}</option>)}</select></Field>{d.loading&&!d.data?<Loading/>:d.error?<ErrorBox message={d.error} retry={d.reload}/>:<Card><ReportList items={d.data?.items||[]} onOpen={rid=>nav('detail','community',rid)}/></Card>}</>;}
export function Progress(){const {id,nav,setDraft,user}=useApp();const r=useData<CaseReport>(id?`/reports/${id}`:null,15000);if(!id)return <MyReports/>;if(r.loading&&!r.data)return <Loading/>;if(r.error)return <ErrorBox message={r.error} retry={r.reload}/>;const d=r.data!;
 return <><PageHead label={d.code} title={d.title}/><State state={d.state}/><Card><p>{d.description}</p><small>{d.area_name} • {date(d.observed_at)}</small>{d.evidence.map(e=><ImageView key={e.id} url={e.url}/>)}</Card><Card><h3>Case timeline</h3><div className="timeline">{d.timeline?.map(t=><div key={t.id}><strong>{nice(t.action)}</strong><p>{t.note}</p><small>{date(t.created_at)}</small></div>)}</div></Card>{d.is_owner&&['draft','needs_evidence'].includes(d.state)&&<Button onClick={()=>{const draft:Draft={...newDraft(user!.id,d.category),client_id:d.client_id,server_id:d.id,server_version:d.version,title:d.title,description:d.description,species:d.species,area_id:d.area_id,observed_at:d.observed_at,latitude:d.latitude===null?'':String(d.latitude),longitude:d.longitude===null?'':String(d.longitude),share_location:d.share_location,consent:d.consent,evidence:d.evidence[0]};setDraft(draft);nav(d.category==='wildlife'?'wildlife':d.category==='wetland'?'wetland':'floodreport');}}>Update requested evidence</Button>}{d.state!=='draft'&&<Button variant="ghost" onClick={()=>nav('community','community',d.id)} icon="chat">Message the case team</Button>}</>;
}

export function CommunityMap(){const {nav}=useApp();const [category,setCategory]=useState('');const d=useMapData({view:'community',category:category||undefined,viewport:true,interval:20000,realtime:false});return <><PageHead title="Your community, in context." subtitle="Only reviewed, current advisories are shown. Pins are area centres."/><div className="tabrow">{['','wildlife','wetland','flood'].map(c=><button key={c} className={'tab '+(category===c?'active':'')} onClick={()=>setCategory(c)}>{nice(c||'all')}</button>)}</div>{d.error?<ErrorBox message={d.error}/>:d.data?<><MapPanel data={d.data} large fit={false} onViewportChange={d.onViewport} onSelect={f=>nav('alertdetail','community',f.id)}/><Card>{d.data.features.map(f=><button key={f.id} className="report-row" onClick={()=>nav('alertdetail','community',f.id)}><Icon name={categoryIcon(f.properties.category)}/><span>{f.properties.title}<small>{f.properties.area_name}</small></span><Icon name="arrow"/></button>)}{!d.data.features.length&&<Empty title="No published map records"/>}</Card></>:<Loading/>}</>;}

export function Messages(){const {id,nav}=useApp();const reports=useData<Collection<CaseReport>>('/reports?mine=true&page_size=100');const d=useData<Collection<Message>>(id?`/reports/${id}/messages`:null,5000);const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function send(e:FormEvent){e.preventDefault();setBusy(true);try{await post(`/reports/${id}/messages`,{body:text});setText('');d.reload();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><PageHead title="Case conversations" subtitle="Private messages between you and authorised case staff."/><Field label="Choose a submitted report"><select value={id} onChange={e=>nav('community','community',e.target.value)}><option value="">Choose a case</option>{reports.data?.items.filter(r=>r.state!=='draft').map(r=><option key={r.id} value={r.id}>{r.code} • {r.title}</option>)}</select></Field>{!id?<Empty title="Choose a case to continue"/>:<><Card className="messages">{d.data?.items.map(m=><div className={'chatbubble '+(m.is_mine?'me':'')} key={m.id}><strong>{m.sender_label}</strong><p>{m.body}</p><small>{date(m.created_at)}</small></div>)}{!d.data?.items.length&&<small>No messages yet. Ask a question about this case.</small>}</Card><form onSubmit={send} className="stack"><Field label="Your message"><textarea value={text} required minLength={1} maxLength={3000} onChange={e=>setText(e.target.value)}/></Field>{(error||d.error)&&<ErrorBox message={error||d.error}/>}<Button disabled={busy} type="submit">Send message</Button></form></>}</>;
}

export function Profile(){const {user,setUser,areas,notify,config}=useApp();const [name,setName]=useState(user!.name),[followed,setFollowed]=useState(user!.preferences.followed_areas||[]),[phone,setPhone]=useState(user!.preferences.phone||''),[sms,setSms]=useState(user!.preferences.sms_opt_in||false),[inApp,setInApp]=useState(user!.preferences.in_app!==false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[oldPassword,setOldPassword]=useState(''),[newPassword,setNewPassword]=useState('');
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const result=await api<{user:User}>('/auth/preferences',{method:'PUT',body:JSON.stringify({name,followed_areas:followed,phone,sms_opt_in:sms,in_app:inApp,language:'en'})});setUser(result.user);notify('Preferences saved to your account.');setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function password(e:FormEvent){e.preventDefault();try{await post('/auth/password',{current_password:oldPassword,new_password:newPassword});setUser(null);notify('Password changed. Sign in again on each device.');}catch(e){setError((e as Error).message);}}
 return <><PageHead title="You are in control." subtitle="Your account, communities and notification preferences."/><Card><div className="row"><span className="avatar large">{user!.name.slice(0,1)}</span><div><h3>{user!.name}</h3><small>{user!.email}</small><div className="chips">{user!.roles.map(r=><Badge key={r}>{nice(r)}</Badge>)}</div></div></div></Card><form onSubmit={save} className="stack"><Field label="Display name"><input value={name} required minLength={2} onChange={e=>setName(e.target.value)}/></Field><fieldset><legend>Follow communities</legend>{areas.map(a=><label className="checkrow" key={a.id}><input type="checkbox" checked={followed.includes(a.id)} onChange={e=>setFollowed(e.target.checked?[...followed,a.id]:followed.filter(id=>id!==a.id))}/>{a.name}</label>)}</fieldset><label className="checkrow"><input type="checkbox" checked={inApp} onChange={e=>setInApp(e.target.checked)}/>Highlight new in-app advisories.</label><Field label="Phone number (optional)" hint="International format, for example +256…"><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={20}/></Field><label className="checkrow"><input type="checkbox" checked={sms} onChange={e=>setSms(e.target.checked)}/>I opt in to optional SMS for my followed communities.</label><Notice tone="amber">SMS provider: {config?.sms||'disabled'}. An opt-in does not mean a message was sent. In-app advisories remain available.</Notice><Field label="Interface language"><select value="en" disabled><option>English</option></select></Field>{error&&<ErrorBox message={error}/>}<Button type="submit" disabled={busy}>Save preferences</Button></form><details><summary>Change password</summary><form className="stack" onSubmit={password}><Field label="Current password"><input type="password" value={oldPassword} onChange={e=>setOldPassword(e.target.value)} required autoComplete="current-password"/></Field><Field label="New password (12+ characters)"><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required minLength={12} autoComplete="new-password"/></Field><Button type="submit" variant="ghost">Change password & sign out</Button></form></details><Button variant="ghost" onClick={async()=>{await removeDraft(user!.id);notify('Draft removed from this browser.');}}>Clear my saved device draft</Button></>;
}

export function Help(){const {nav}=useApp();return <><PageHead label="HELP & SAFETY" title="People first. Always." subtitle="A responsible way to report and follow up."/><Notice tone="amber">EcoGuard is not an emergency-dispatch service. Follow local emergency procedures and contact the relevant responders through established channels.</Notice>{[['What happens after I report?','Your report is private. Assigned staff examine the evidence. Only a separate authorised publisher can issue a reviewed public advisory.'],['Can AI confirm an animal?','Image assistance may suggest a candidate species or return unknown/unavailable. A human reviewer must decide. Do not rely on a model output for personal safety.'],['Can I report offline?','You can save a form and photo locally on this device. Sign-in, upload, submission and new advisories need connectivity. Syncing is an explicit action, never a false success message.'],['Who sees my image or precise location?','Only you and staff with the correct role and assigned area can view case evidence. Community map markers use area centres and published advisory text.'],['How do I report safely?','Do not approach wildlife, enter floodwater, trespass or confront people. Record observations only when you can do so safely.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<Button variant="ghost" onClick={()=>nav('stakeholders')}>Who is involved?</Button><Button variant="ghost" onClick={()=>nav('screens')}>View all application pages</Button></>;}
