import React from 'react';
import {useApp} from '../lib/context';
import {PageHead,Card,Notice,Button,Icon} from '../components/ui';

const COMMUNITY_PAGES=[['home','home','Community home','Dashboard of advisories and your contributions.'],['upload','camera','Report a sighting','Attach an existing image without approaching wildlife.'],['identify','search','Image assistance','Request a candidate identity. A reviewer decides.'],['wildlife','file','Wildlife report details','Describe what you observed.'],['wetland','leaf','Wetland report details','Record an observed change in a wetland.'],['floodreport','drop','Water report details','Share a flood or water observation.'],['review','check','Final check','Consent, then submit for human review.'],['success','check','Submitted','Confirmation with your real report reference.'],['myreports','file','My reports','Every report you have submitted.'],['detail','search','Report progress','Status, evidence and case timeline.'],['alerts','bell','Advisories','Reviewed, human-published updates.'],['alertdetail','bell','Advisory detail','Source, area and expiry for one advisory.'],['map','map','Community map','Published records at area-centre precision.'],['community','chat','Case messages','Private messages with assigned staff.'],['profile','user','Profile','Preferences, communities and password.'],['help','help','Help and safety','Reporting guidance and limits.'],['stakeholders','grid','Stakeholders','Who the proposed pilot involves.'],['screens','grid','All pages','This index.']] as const;
const WORKSPACE_PAGES=[['dashboard','grid','Overview','Scoped counts and latest reports.'],['reports','file','Reports and cases','Search, filter and export.'],['wildlife','paw','Wildlife evidence','Gallery of image evidence awaiting review.'],['wetland','leaf','Wetland workspace','Observations and follow-up actions.'],['flood','drop','Flood information','Draft, review and publish sourced updates.'],['verify','check','Verification','Human review decisions for a case.'],['map','map','Incident map','Staff positions stay private.'],['alerts','bell','Alert centre','Advisory drafting, privacy check and publication.'],['analytics','chart','Analytics','Process metrics calculated from API records.'],['team','settings','Team and settings','Access, areas, audit and integrations.']] as const;

export function Screens(){
  const{nav,user}=useApp();
  const staff=!!user&&user.roles.some(r=>['reviewer','publisher','responder','admin'].includes(r));
  return <><PageHead label="APPLICATION INDEX" title="Every page in this release." subtitle="Each screen below is connected to the EcoGuard API. Nothing here is a static mockup."/>
    <Card><h3>Community application</h3><div className="report-list">{COMMUNITY_PAGES.map(([p,i,t,sub])=><button className="report-row" key={p} onClick={()=>nav(p,'community')}><span className="iconbox"><Icon name={i} size={19}/></span><div className="grow"><strong>{t}</strong><small>{sub}</small></div><Icon name="arrow" size={17}/></button>)}</div></Card>
    {staff&&<Card><h3>Shared workspace</h3><div className="report-list">{WORKSPACE_PAGES.map(([p,i,t,sub])=><button className="report-row" key={p} onClick={()=>nav(p,'workspace')}><span className="iconbox"><Icon name={i} size={19}/></span><div className="grow"><strong>{t}</strong><small>{sub}</small></div><Icon name="arrow" size={17}/></button>)}</div></Card>}
    <Notice tone="blue">Screens marked as concept illustrations in earlier design files are now driven by live API records. Image assistance stays unavailable until an operator configures a model.</Notice>
    <Button variant="ghost" icon="back" onClick={()=>nav('help')}>Back to help and safety</Button>
  </>;
}
