import React,{useEffect,useState,useMemo} from 'react';
import {api,post,signIn,ApiError,downloadExport} from './lib/api';
import {useData} from './lib/useData';
import {useRealtimeTick} from './lib/useRealtime';
import type {Collection,Advisory,Dashboard,CaseReport,Category,User,Message} from './lib/types';
import './styles.css';

type Role='reporter'|'reviewer'|'publisher'|'responder'|'admin';

/* ------------------------------------------------------------------ icons */
const PATHS:Record<string,string>={
 leaf:'M20 4C11 3 4 7 4 13a7 7 0 0 0 7 7c6 0 10-7 9-16ZM4 20 15 9',
 paw:'M8 14c2-3 6-3 8 0 2 3 4 5 1 6-2 1-3-1-5-1s-3 2-5 1c-3-1-1-3 1-6ZM5 9a2 3 0 1 0 0 .1M10 5a2 3 0 1 0 0 .1M15 5a2 3 0 1 0 0 .1M20 9a2 3 0 1 0 0 .1',
 home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',
 bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5l-2 3ZM10 21h4',
 camera:'M4 7h4l2-3h4l2 3h4v14H4V7ZM16 13a4 4 0 1 0-8 0 4 4 0 0 0 8 0Z',
 map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5ZM9 3v16M15 5v16',
 pin:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0ZM15 10a3 3 0 1 0-6 0 3 3 0 0 0 6 0Z',
 water:'M3 8c3-4 4 4 8 0s5 4 10 0M3 14c3-4 4 4 8 0s5 4 10 0M3 20c3-4 4 4 8 0s5 4 10 0',
 plus:'M12 4v16M4 12h16',
 chevron:'m9 5 7 7-7 7',
 left:'m15 5-7 7 7 7',
 search:'M17 10a7 7 0 1 0-14 0 7 7 0 0 0 14 0ZM15 15l6 6',
 check:'m5 12 4 4L19 6',
 user:'M16 7a4 4 0 1 0-8 0 4 4 0 0 0 8 0ZM4 21v-3c0-6 16-6 16 0v3',
 users:'M12 7a4 4 0 1 0-8 0 4 4 0 0 0 8 0ZM1 21v-3c0-6 14-6 14 0v3M17 3a4 4 0 0 1 0 8M18 14c3 0 5 2 5 4v3',
 chart:'M3 3v18h19M7 17V9M12 17V5M17 17v-6',
 file:'M6 3h8l5 5v13H6V3ZM14 3v6h5M9 13h7M9 17h7',
 shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-4 10 3 3 5-6',
 settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3ZM16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0Z',
 logout:'M10 3H4v18h6M9 12h12M17 8l4 4-4 4',
 upload:'M12 16V3M7 8l5-5 5 5M4 16v5h16v-5',
 image:'M3 3h18v18H3V3ZM3 16l6-6 5 5 3-3 4 4M16 7h.01',
 clock:'M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0ZM12 6v6l4 2',
 chat:'M3 4h18v13H8l-5 4V4ZM7 8h10M7 12h7',
 help:'M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0ZM9 8c0-4 8-3 6 1-1 2-3 1-3 5M12 18h.01',
 filter:'M3 4h18l-7 8v8l-4-2v-6L3 4',
 download:'M12 3v13M7 11l5 5 5-5M3 17v4h18v-4',
 lock:'M6 10h12v11H6V10ZM8 10V6a4 4 0 0 1 8 0v4',
 wifi:'M2 8c6-6 14-6 20 0M5 12c4-4 10-4 14 0M8 16c2-2 6-2 8 0M12 20h.01',
 more:'M5 12h.01M12 12h.01M19 12h.01',
 star:'m12 2 3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1 3-7',
 sun:'M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0ZM12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2'
};
function Icon({n='leaf',s=20}:{n?:string;s?:number}){return <svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.7} strokeLinecap="round" strokeLinejoin="round"><path d={PATHS[n]||PATHS.leaf}/></svg>}

/* ------------------------------------------------------------ primitives */
const nice=(text:string)=>text.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmtDate=(iso?:string|null)=>{const d=iso?new Date(iso):new Date();return d.toLocaleDateString('en-UG',{day:'numeric',month:'short'})+' '+d.getFullYear()}; 
const timeAgo=(iso:string)=>{const s=(Date.now()-Date.parse(iso))/1000;if(!isFinite(s))return '';if(s<3600)return Math.max(1,Math.round(s/60))+' min ago';if(s<86400)return Math.round(s/3600)+'h ago';return Math.round(s/86400)+'d ago'};
const catIcon=(c:string)=>c==='wildlife'?'paw':c==='flood'?'water':'leaf';
const catTone=(c:string)=>c==='wildlife'?'amber':c==='flood'?'blue':'';
const catName=(c:string)=>c==='wildlife'?'Wildlife':c==='flood'?'Flood':'Wetland';
const stateTone=(s:string)=>['verified','published','closed','completed'].includes(s)?'':['rejected','retracted','failed'].includes(s)?'red':['under_review','needs_evidence','submitted','unavailable'].includes(s)?'amber':'gray';
function Tag({children,tone=''}:{children:React.ReactNode;tone?:string}){return <span className={'tag '+tone}>{children}</span>}
function Box({children,className='',style}:{children:React.ReactNode;className?:string;style?:React.CSSProperties}){return <section className={'card '+className} style={style}>{children}</section>}
function IconBox({n,tone=''}:{n:string;tone?:string}){return <span className={'iconbox '+tone}><Icon n={n} s={21}/></span>}
function Notice({tone='',children}:{tone?:string;children:React.ReactNode}){return <div className={'notice '+tone}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function CheckRow({checked,onChange,children}:{checked?:boolean;onChange?:()=>void;children:React.ReactNode}){return <label className="checkrow"><input type="checkbox" checked={checked} onChange={onChange}/><span>{children}</span></label>}
function Btn({children,ghost=false,small=false,wide=false,amber=false,red=false,icon,disabled=false,onClick,type='button',className=''}:{children?:React.ReactNode;ghost?:boolean;small?:boolean;wide?:boolean;amber?:boolean;red?:boolean;icon?:string;disabled?:boolean;onClick?:React.MouseEventHandler<HTMLButtonElement>;type?:'button'|'submit';className?:string}){
 let c='btn ';if(ghost)c+='ghost ';if(small)c+='small ';if(wide)c+='wide ';if(amber)c+='amber ';if(red)c+='red ';c+=className;
 return <button type={type} className={c} onClick={onClick} disabled={disabled}>{icon&&<Icon n={icon} s={18}/>}{children}</button>;
}
function LinkBtn({children,onClick}:{children:React.ReactNode;onClick?:()=>void}){return <button className="link" onClick={onClick}>{children}</button>}
function Row({children,between=false,className='',style}:{children:React.ReactNode;between?:boolean;className?:string;style?:React.CSSProperties}){return <div className={'row '+(between?'between ':'')+className} style={style}>{children}</div>}
function MTitle({t,p}:{t:React.ReactNode;p?:React.ReactNode}){return <div className="mtitle"><h1>{t}</h1>{p?<p>{p}</p>:null}</div>}
function PHead({label,title,sub,action}:{label?:string;title:string;sub?:string;action?:React.ReactNode}){return <div className="pagehead"><div>{label&&<div className="eyebrow">{label}</div>}<h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{action}</div>}
function Stat({n,l,tone=''}:{n:string;l:string;tone?:string}){return <div className="card stat"><span className={'iconbox '+tone}><Icon n={l==='Wildlife reports'?'paw':l==='Flood updates'||l==='Open review'?'clock':l.includes('Wetland')?'leaf':'file'} s={21}/></span><div><strong>{n}</strong><small>{l}</small></div><span className="trend">Live</span></div>}
function Flowline({step=1}:{step?:number}){return <div className="flowline">{[1,2,3,4].map(i=><React.Fragment key={i}>{i>1&&<span className="progress"><i style={{width:i<=step?'100%':'60%'}}/></span>}<span className={'stepnum '+(i<=step?'done':'')}>{i}</span></React.Fragment>)}</div>}
function ToggleRow({label,sub,on,onClick}:{label:React.ReactNode;sub?:string;on:boolean;onClick?:()=>void}){return <div className="listrow" style={{cursor:'pointer'}} onClick={onClick}><div className="grow"><h3>{label}</h3>{sub&&<p>{sub}</p>}</div><button type="button" className={'right toggle '+(on?'':'off')} aria-label={`Toggle ${label}`}/></div>}

/* ------------------------------------------------------------------ toast */
function useToast(){
 const [t,setT]=useState('');
 useEffect(()=>{if(!t)return;const id=setTimeout(()=>setT(''),3500);return()=>clearTimeout(id);},[t]);
 return {toast:(m:string)=>setT(m),node:t?<div className="toast">{t}</div>:null};
}

/* -------------------------------------------------------------------- map */
function SketchMap({h=245}:{h?:number}){
 return <div className="map skymap" style={{height:h}}><svg viewBox="0 0 650 450" preserveAspectRatio="none"><path d="M-30 350Q80 265 150 300T280 280 400 240 510 145 680 130" fill="none" stroke="#c7ddaa" strokeWidth="160"/><path d="M-20 410Q150 300 225 320T410 250 530 120 690 150" fill="none" stroke="#afcede" strokeWidth="43"/><path d="M-20 100Q160 130 190 265T340 430M130 -20 400 470M-20 220 680 300M10 480 550 -20" fill="none" stroke="#fbfaf1" strokeWidth="13"/><path d="M-20 100Q160 130 190 265T340 430M130 -20 400 470M-20 220 680 300M10 480 550 -20" fill="none" stroke="#d6d8c6" strokeWidth="1.5"/><path d="M360 10 410 120 490 100 520 20ZM45 30 100 50 90 150 10 135ZM400 350 520 315 560 425 445 460Z" fill="#b8d3a2" opacity=".6"/></svg><span className="maptag"><Icon n="map" s={13}/> Community view</span><span className="maplabel" style={{top:'38%',left:'12%'}}>COMMUNITY A</span><span className="maplabel" style={{top:'68%',left:'53%'}}>WETLAND ZONE</span><span className="pin amber" style={{top:'29%',left:'61%'}}><Icon n="paw" s={19}/></span><span className="pin" style={{top:'53%',left:'35%'}}><Icon n="leaf" s={19}/></span><span className="pin blue" style={{top:'75%',left:'71%'}}><Icon n="water" s={19}/></span><div className="mapzoom"><button type="button" aria-label="Zoom in">+</button><button type="button" aria-label="Zoom out">−</button></div><span className="mapnote">Illustrative map · Not for navigation</span></div>;
}

/* ------------------------------------------------------------------- hero */
const PROMOS=[['WILDLIFE FIRST','Turn a sighting into a safer response.','Review community-uploaded images, verify wildlife reports and notify the right people.','Review wildlife reports','elephant','wildlife'],['WETLAND GUARDIANS','Make every community report count.','Bring encroachment reports, locations and follow-up actions into one workspace.','Review wetland reports','wetland','wetland'],['COMMUNITY ADVISORIES','Clear updates. Better-informed communities.','Share reviewed flood information and keep a visible record of each advisory.','Open flood advisories','flood','flood']] as const;
function DesktopHero({go}:{go:(p:string)=>void}){
 const [i,setI]=useState(0),[paused,setPaused]=useState(false);
 useEffect(()=>{if(paused)return;const id=setInterval(()=>setI(n=>(n+1)%3),6000);return()=>clearInterval(id);},[paused]);
 const p=PROMOS[i];
 return <div className="hero"><div className="heroimg" style={{backgroundImage:`url(/assets/${p[4]}.jpg)`}}></div><div className="leaves"></div><div className="herocontent"><div className="eyebrow">{p[0]}</div><h2>{p[1]}</h2><p>{p[2]}</p><Btn icon={catIcon(p[5])} onClick={()=>go(p[5])}>{p[3]}</Btn></div><div className="carouselnav"><button type="button" className="arrowbtn" aria-label="Previous banner" onClick={()=>setI((i+2)%3)}><Icon n="left" s={13}/></button>{PROMOS.map((_,j)=><button type="button" key={j} aria-label={`Banner ${j+1}`} className={'carodot '+(i===j?'active':'')} onClick={()=>setI(j)}></button>)}<button type="button" className="arrowbtn" aria-label="Next banner" onClick={()=>setI((i+1)%3)}><Icon n="chevron" s={13}/></button><button type="button" className="arrowbtn" aria-label={paused?'Play slideshow':'Pause slideshow'} onClick={()=>setPaused(!paused)}>{paused?'▶':'Ⅱ'}</button></div></div>;
}
function MobileHero({go}:{go:(p:string)=>void}){return <div className="hero"><div className="heroimg" style={{backgroundImage:'url(/assets/elephant.jpg)'}}></div><div className="herocontent"><div className="eyebrow">WILDLIFE FIRST</div><h2>A sighting can<br/>make a difference.</h2><p>Share an existing photo safely.</p><Btn onClick={()=>go('upload')}>Report wildlife</Btn></div></div>}

/* ---------------------------------------------------------------- rabbits */
const DEMO_ROWS=[['EG-W-024','Possible elephant','Community A','Wildlife','Under review','amber'],['EG-E-011','Possible encroachment','Wetland zone A','Wetland','Assigned',''],['EG-F-007','Rising-water report','Community B','Flood','Reviewed','blue'],['EG-W-019','Unknown animal','Community C','Wildlife','Needs evidence','amber']];
type TRow={code:string;title:string;area:string;cat:string;tone:string;st:string;demo:boolean};
const tRow=(r:CaseReport):TRow=>({code:r.code||r.id,title:r.title,area:r.area_name||'',cat:catName(r.category),tone:stateTone(r.state),st:nice(r.state),demo:false});
const dRow=(r:string[]):TRow=>({code:r[0],title:r[1],area:r[2],cat:r[3],tone:r[5],st:r[4],demo:true});

/* ================================================================ ROOT APP */
const COMMUNITY_ROUTES=['home','upload','identify','sighting','review','success','alerts','alert-detail','map','wetland','flood','my-reports','progress','messages','settings','help'];
function App(){
 const [route,setRoute]=useState<string>(location.hash.slice(1)||'welcome');
 const [user,setUser]=useState<User|null>(null);
 const [err,setErr]=useState('');
 useEffect(()=>{const on=()=>setRoute(location.hash.slice(1)||'welcome');addEventListener('hashchange',on);return()=>removeEventListener('hashchange',on)},[]);
 useEffect(()=>{api<{user:User}>('/auth/me').then(x=>setUser(x.user)).catch(()=>{});const onSession=()=>{setUser(null);setRoute('welcome')};addEventListener('session-expired',onSession);return()=>removeEventListener('session-expired',onSession)},[]);
 const go=(p:string)=>{location.hash=p};
 const staff=user?user.roles.some((r:Role)=>['reviewer','publisher','responder','admin'].includes(r)):false;
 const authed=!!user;
 if(route==='welcome')return <WelcomePage go={go}/>;
 if(route==='signin'||!authed)return <SignInPage onDone={u=>{setUser(u);go(u.roles.some((r:Role)=>['reviewer','publisher','responder','admin'].includes(r))?'dashboard':'home')}}/>;
 if(COMMUNITY_ROUTES.includes(route))return <MobileApp user={user!} route={route} go={go} onLogout={()=>{post('/auth/logout',{}).finally(()=>{setUser(null);go('welcome')})}}/>;
 return <DesktopApp user={user!} route={route} go={go} onLogout={()=>{post('/auth/logout',{}).finally(()=>{setUser(null);go('welcome')})}}/>;
}
export default App;

/* ============================================================ MOBILE APP */
function Brand({onClick}:{onClick?:()=>void}){return <div className="brand" style={onClick?{cursor:'pointer'}:undefined} onClick={onClick}><span className="mark"><Icon n="leaf" s={24}/></span><span>EcoGuard<small>UGANDA</small></span></div>}
function MobileApp({user,route,go,onLogout}:{user:User;route:string;go:(p:string)=>void;onLogout:()=>void}){
 const {toast,node}=useToast();
 const content=<>
  {route==='home'&&<HomeScreen go={go}/>}
  {route==='upload'&&<UploadScreen go={go}/>}
  {route==='identify'&&<IdentifyScreen go={go}/>}
  {route==='sighting'&&<SightingScreen go={go}/>}
  {route==='review'&&<ReviewScreen go={go}/>}
  {route==='success'&&<SuccessScreen go={go}/>}
  {route==='alerts'&&<AlertsScreen go={go}/>}
  {route==='alert-detail'&&<AlertDetailScreen go={go}/>}
  {route==='map'&&<MapScreen go={go}/>}
  {route==='wetland'&&<WetlandScreen go={go}/>}
  {route==='flood'&&<FloodScreen go={go}/>}
  {route==='my-reports'&&<MyReportsScreen go={go}/>}
  {route==='progress'&&<DetailScreen go={go}/>}
  {route==='messages'&&<MessagesScreen go={go} toast={toast}/>}
  {route==='settings'&&<SettingsScreen go={go} user={user} toast={toast}/>}
  {route==='help'&&<HelpScreen go={go}/>}
 </>;
 const act=['upload','identify','sighting','review','success','wildlife'].includes(route)?'upload':['my-reports','progress','wetland','flood'].includes(route)?'upload':route==='map'?'map':route==='alerts'||route==='alert-detail'?'alerts':route==='settings'?'settings':'home';
 return <div className="backdrop"><div className="app-mobile mobile"><header className="mnav"><Brand onClick={()=>go('home')}/><button type="button" aria-label="Alerts" onClick={()=>go('alerts')}><Icon n="bell" s={23}/></button></header><main className="mcontent">{content}</main><nav className="mbottom">{[['home','home','Home'],['map','map','Map'],['upload','plus','Report'],['alerts','bell','Alerts'],['settings','user','Profile']].map(([k,i,l])=><button key={k} className={act===k?'active':''} onClick={()=>go(k)}><Icon n={i} s={21}/><span>{l}</span></button>)}</nav></div>{node}</div>;
}

/* welcome */
function WelcomePage({go}:{go:(p:string)=>void}){return <div className="backdrop"><div className="app-mobile mobile"><header className="mnav"><Brand/></header><main className="mcontent"><div style={{height:8}}></div><div className="mhero-welcome"><img src="/assets/elephant.jpg" alt="Elephant illustration"/><span>People. Wildlife.<br/>Safer together.</span></div><MTitle t={<>Small reports.<br/>Shared protection.</>} p="Report wildlife, wetland threats and flood concerns through one community app."/><div className="mquick"><button type="button"><Icon n="paw"/>Wildlife</button><button type="button"><Icon n="leaf"/>Wetlands</button><button type="button"><Icon n="water"/>Floods</button></div><Btn wide onClick={()=>go('signin')}>Get started <Icon n="chevron" s={16}/></Btn><Btn wide ghost onClick={()=>go('home')}>Explore example screens</Btn><p className="small" style={{textAlign:'center'}}>Application concept · No field hardware required</p></main></div></div>}

/* sign in */
function SignInPage({onDone}:{onDone:(u:User)=>void}){
 const [register,setRegister]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[consent,setConsent]=useState(true),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setErr('');try{onDone(await signIn(email,password,register?name:undefined));}catch(e){setErr(e instanceof Error?e.message:'Sign-in failed')}finally{setBusy(false)}}
 return <div className="backdrop"><div className="app-mobile mobile"><header className="mnav"><Brand/></header><main className="mcontent"><MTitle t="Welcome to EcoGuard" p="Sign in or create your community account."/><Notice><Icon n="shield" s={17}/> Your identity is not shown on public maps.</Notice><form className="stack" onSubmit={submit}>{register&&<Field label="Full name"><input value={name} onChange={e=>setName(e.target.value)} required minLength={2} placeholder="Community member"/></Field>}<Field label={register?'Email address':'Email address'}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" placeholder="you@example.org"/></Field><Field label="Password"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={register?12:1} autoComplete={register?'new-password':'current-password'} placeholder="••••••••••••"/></Field><CheckRow checked={consent} onChange={()=>setConsent(!consent)}>I agree to the privacy notice and to receive updates about my reports.</CheckRow>{err&&<Notice tone="red">{err}</Notice>}<Btn type="submit" wide disabled={busy}>{busy?'Connecting…':'Continue '+<Icon n="chevron" s={16}/>}</Btn></form><Box><h3>{register?'Account setup':'Verification step'}</h3><p style={{marginTop:7}}>{register?'An invite role is assigned by the workspace administrator.' :'A one-time code confirms your phone number in the planned application.'}</p></Box><LinkBtn onClick={()=>setRegister(!register)}>{register?'Already have an account? Sign in':'Need an account? Register'}</LinkBtn><p className="small">Sign-in and registration use a real account in this application.</p></main></div></div>;
}

/* home */
function HomeScreen({go}:{go:(p:string)=>void}){const alerts=useData<Collection<Advisory>>('/advisories',20000);const a=alerts.data?.items?.[0];return <><MTitle t="Hello, neighbour." p="Stay informed. Share what you see."/><MobileHero go={go}/><div className="mquick"><button type="button" onClick={()=>go('upload')}><Icon n="paw"/>Wildlife</button><button type="button" onClick={()=>go('wetland')}><Icon n="leaf"/>Wetlands</button><button type="button" onClick={()=>go('flood')}><Icon n="water"/>Floods</button></div><Row between><h3>Community updates</h3><Tag>Live</Tag></Row>{a?<Box><Row>{IconBox({n:catIcon(a.category),tone:catTone(a.category)})}<div><h3>{a.title}</h3><p>{a.area_name} · Reviewed example</p></div></Row><p style={{margin:'10px 0'}}>{a.body}</p><LinkBtn onClick={()=>go('alert-detail')}>Read advisory <Icon n="chevron" s={13}/></LinkBtn></Box>:<Box><Row>{IconBox({n:'paw',tone:'amber'})}<div><h3>Wildlife advisory</h3><p>Community A · Reviewed example</p></div></Row><p style={{margin:'10px 0'}}>Keep your distance. Read the latest update from the assigned reviewer.</p><LinkBtn onClick={()=>go('alert-detail')}>Read advisory <Icon n="chevron" s={13}/></LinkBtn></Box>}<button type="button" className="pillbutton" onClick={()=>go('my-reports')}><span><Icon n="file" s={16}/> My report progress</span><Icon n="chevron" s={15}/></button></>}

/* upload */
function UploadScreen({go}:{go:(p:string)=>void}){const [file,setFile]=useState<string>('');return <><MTitle t="Identify wildlife" p="Upload an existing image. Do not approach an animal to take a photo."/><Flowline step={1}/><label className="uploadbox"><Icon n="image" s={39}/><h3>Add a wildlife photo</h3><p>JPG or PNG · Suggested limit: 10 MB<br/>Use an image you have permission to share.</p><Btn ghost onClick={(e)=>{e.preventDefault();(document.getElementById('wildfile') as HTMLInputElement|null)?.click();}}>Choose a photo <Icon n="upload" s={16}/></Btn><input id="wildfile" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)setFile(URL.createObjectURL(f))}}/></label>{file&&<Row><img className="photo" style={{width:67,height:76}} src={file} alt="Selected wildlife photo"/><div className="grow"><strong style={{fontSize:14}}>Sample image selected</strong><p className="small">Local preview · Not yet uploaded</p><Tag tone="amber">Ready to review</Tag></div></Row>}<Notice tone="amber">AI suggests a possible species from your image. A reviewer confirms the report before any public advisory.</Notice><Btn wide onClick={()=>go('identify')}>Review identification <Icon n="chevron" s={16}/></Btn><Btn wide ghost onClick={()=>go('sighting')}>Report without a photo</Btn></>}

/* identify */
function IdentifyScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Check the suggestion" p="AI assistance is not a verified wildlife report."/><div className="reviewimg"><img src="/assets/elephant.jpg" alt="Elephant evidence illustration"/><div className="bounding"><b>Elephant? · Demo suggestion</b></div></div><Box><Row between><h3>Possible elephant</h3><Tag tone="amber">Unverified</Tag></Row><p style={{margin:'10px 0'}}>Example result only. The model still needs training and local evaluation.</p><Row between><span className="small">Is the suggestion useful?</span><LinkBtn onClick={()=>{}}>Suggest correction</LinkBtn></Row></Box><Notice tone="blue">Not sure? Continue with “Unknown animal”. Never guess to speed up an alert.</Notice><Btn wide onClick={()=>go('sighting')}>Use suggestion & continue</Btn><Btn wide ghost onClick={()=>go('sighting')}>Continue as unknown animal</Btn></>}

/* sighting */
function SightingScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Report the sighting" p="Step 2 of 4 · Add the facts you know."/><Row><img src="/assets/elephant.jpg" className="photo" style={{width:58,height:67}} alt="Evidence"/><div><strong>Possible elephant</strong><p className="small">AI suggestion · Needs review</p></div></Row><Field label="Animal / species"><select><option>Possible elephant</option><option>Buffalo</option><option>Unknown animal</option></select></Field><Field label="Approximate area"><select><option>Pilot community A</option><option>Community B</option><option>Community C</option></select></Field><Field label="When was it seen?"><input defaultValue="20 Sep 2026, 09:10"/></Field><Field label="What did you observe?"><textarea defaultValue="Seen near the field boundary. No approach made."/></Field><CheckRow checked>Share a precise location only with an authorised reviewer.</CheckRow><Btn wide onClick={()=>go('review')}>Review report <Icon n="chevron" s={16}/></Btn></>}

/* review */
function ReviewScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Review before sending" p="Step 3 of 4 · Check your report and privacy choices."/><Box><Row between><h3>Wildlife sighting</h3><Tag tone="gray">Draft</Tag></Row><div className="line"></div><div className="stack"><div><small>SPECIES</small><p>Possible elephant · Unverified</p></div><div><small>LOCATION</small><p>Community A · approximate area</p></div><div><small>OBSERVATION</small><p>Seen near the field boundary.</p></div></div></Box><Box><h3>Privacy controls</h3><ToggleRow label="Hide my identity" sub="From community views" on/><ToggleRow label="Protect exact location" sub="Reviewer access only" on/></Box><Notice>An advisory is not issued automatically. A reviewer checks the evidence first.</Notice><Btn wide onClick={()=>go('success')}>Submit example report</Btn></>}

/* success */
function SuccessScreen({go}:{go:(p:string)=>void}){return <><div style={{padding:'19px 0 6px',textAlign:'center'}}><span className="iconbox" style={{width:76,height:76,borderRadius:'50%',margin:'auto',position:'static'}}><Icon n="check" s={40}/></span></div><MTitle t="Your report is in review." p="Thank you for sharing responsibly."/><Box><Row between><h3>EG-W-024</h3><Tag>Example</Tag></Row><p style={{margin:'9px 0'}}>Community A · Wildlife sighting</p><div className="timeline"><div><strong>1. Submitted</strong><p>Report saved to the review queue.</p></div><div><strong>2. Awaiting verification</strong><p>An authorised reviewer checks the details.</p></div><div><strong>3. Response update</strong><p>You receive the outcome or a question.</p></div></div></Box><Notice tone="blue">No real report has been sent. This screen demonstrates the proposed submission flow.</Notice><Btn wide onClick={()=>go('progress')}>Track report progress</Btn><Btn wide ghost onClick={()=>go('home')}>Back to home</Btn></>}

/* alerts */
function AlertsScreen({go}:{go:(p:string)=>void}){const d=useData<Collection<Advisory>>('/advisories',20000);const [tab,setTab]=useState('all');const items=d.data?.items||[];return <><MTitle t="Your alerts" p="Reviewed updates for your selected communities."/><div className="tabrow"><button className={'tab '+(tab==='all'?'active':'')} onClick={()=>setTab('all')}>All</button><button className={'tab '+(tab==='wildlife'?'active':'')} onClick={()=>setTab('wildlife')}>Wildlife</button><button className={'tab '+(tab==='flood'?'active':'')} onClick={()=>setTab('flood')}>Flood</button></div>{items.length?items.filter(a=>tab==='all'||a.category===tab).map(a=><Box key={a.id}><Row>{IconBox({n:catIcon(a.category),tone:catTone(a.category)})}<div><h3>{a.title}</h3><p>{a.area_name} · {timeAgo(a.created_at)}</p></div></Row><p style={{margin:'11px 0'}}>{a.body}</p><Row between><Tag tone={catTone(a.category)}>{nice(a.state)}</Tag><LinkBtn onClick={()=>go('alert-detail')}>Open <Icon n="chevron" s={14}/></LinkBtn></Row></Box>):<><Box><Row>{IconBox({n:'paw',tone:'amber'})}<div><h3>Wildlife advisory</h3><p>Community A · 10 min ago</p></div></Row><p style={{margin:'11px 0'}}>A reviewed sighting has been shared for awareness. Do not approach wildlife.</p><Row between><Tag tone="amber">Reviewed example</Tag><LinkBtn onClick={()=>go('alert-detail')}>Open <Icon n="chevron" s={14}/></LinkBtn></Row></Box><Box><Row>{IconBox({n:'water',tone:'blue'})}<div><h3>Flood information</h3><p>River-side zone · 35 min ago</p></div></Row><p style={{margin:'10px 0'}}>A community report is being reviewed. Refer to official safety guidance.</p><Tag tone="blue">Information update</Tag></Box><Box><Row>{IconBox({n:'check'})}<div><h3>Your report was reviewed</h3><p>EG-W-018 · Yesterday</p></div></Row></Box></>}<p className="small">All notifications shown are illustrative.</p></>}

/* alert detail */
function AlertDetailScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Wildlife advisory" p="Example only · Community A"/><Row between><Tag tone="amber">Reviewed</Tag><span className="small">Updated 09:25</span></Row><img className="mphoto" src="/assets/elephant.jpg" alt="Wildlife illustration"/><Box><h3>Possible wildlife nearby</h3><p style={{marginTop:9}}>A reviewer has assessed a community report. The location below is generalised.</p><div className="line"></div><Row><Icon n="pin" s={16}/><span style={{fontSize:13}}>Community A boundary area</span></Row></Box><Notice tone="amber"><strong>Stay at a safe distance.</strong><br/>Do not approach, feed or attempt to chase wildlife. Follow the relevant responder’s guidance.</Notice><Btn wide onClick={()=>go('map')}>View approximate area</Btn><Btn wide ghost onClick={()=>go('help')}>Read safety guidance</Btn></>}

/* mobile map */
function MapScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Community map" p="Wildlife, wetland and flood reports in one view."/><div className="tabrow"><button className="tab active">All</button><button className="tab">Wildlife</button><button className="tab">Flood</button></div><SketchMap h={315}/><Box><Row>{IconBox({n:'paw',tone:'amber'})}<div><h3>Wildlife report · EG-W-024</h3><p>Community A · Location generalised</p></div></Row><Row between><span><Tag tone="amber">Under review</Tag></span><LinkBtn onClick={()=>go('progress')}>View report</LinkBtn></Row></Box><Notice>Public views hide exact wildlife coordinates and reporter identities.</Notice><p className="small">Illustrative positions. This map is not a live monitoring feed.</p></>}

/* wetland form */
function WetlandScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Report a wetland issue" p="Record observations without entering an unsafe area."/><Row>{IconBox({n:'leaf'})}<div><h3>Wetland guardian</h3><p className="small">Community reporting</p></div></Row><Field label="Type of concern"><select><option>Possible encroachment</option><option>Dumping</option><option>Draining</option><option>Other</option></select></Field><Field label="Approximate location"><input defaultValue="Pilot wetland zone A"/></Field><Field label="Describe what you saw"><textarea defaultValue="New soil and construction materials near the wetland edge."/></Field><label className="uploadbox" style={{padding:16}}><div className="row"><Icon n="image" s={22}/><strong style={{fontSize:13}}>Optional photo attachment</strong></div><p>Upload only from a safe location.</p></label><Notice>Reports describe observations, not confirmed offences. A case officer reviews each report.</Notice><Btn wide onClick={()=>go('review')}>Continue to review</Btn></>}

/* flood */
function FloodScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Flood information" p="Community observations and reviewed advisories."/><Box><div className="card" style={{background:'#edf5f6',padding:15}}><Row>{IconBox({n:'water',tone:'blue'})}<div><h3>River-side community</h3><p>Advisory example · 20 Sep</p></div></Row><p style={{margin:'13px 0'}}>Rising-water reports received. A case officer is checking the information.</p><Tag tone="blue">Review in progress</Tag></div></Box><Box><h3>Report water conditions</h3><div style={{height:12}}></div><Field label="Your observation"><select><option>Water is rising</option><option>Water has receded</option><option>Road appears flooded</option></select></Field><div style={{height:12}}></div><Field label="Area"><input defaultValue="Community B, river-side"/></Field><Btn wide onClick={()=>go('review')}>Review observation</Btn></Box><Notice tone="blue">This is not a sensor reading or a guaranteed flood forecast. Official advisories and timestamps must remain visible.</Notice><Btn wide ghost onClick={()=>go('help')}>Read flood safety information</Btn></>}

/* my reports */
function MyReportsScreen({go}:{go:(p:string)=>void}){const d=useData<Collection<CaseReport>>('/reports?mine=true&page_size=100',20000);const items=d.data?.items||[];const awaiting=items.filter(r=>['submitted','under_review','needs_evidence'].includes(r.state)).length;return <><MTitle t="My reports" p="Track what you shared and what happened next."/><div className="grid2"><Box><strong style={{fontSize:29}}>{String(items.length||6).padStart(2,'0')}</strong><p>Example reports</p></Box><Box><strong style={{fontSize:29}}>{String(awaiting||2).padStart(2,'0')}</strong><p>Awaiting review</p></Box></div><div className="tabrow"><button className="tab active">All</button><button className="tab">In review</button><button className="tab">Resolved</button></div><Box className="card-list">{[...items.map(r=><div key={r.id} className="listrow" onClick={()=>go('progress')} style={{cursor:'pointer'}}>{IconBox({n:catIcon(r.category),tone:catTone(r.category)})}<div className="grow"><h3>{r.title}</h3><p>{r.code} · {r.area_name}</p><div style={{marginTop:6}}><Tag tone={stateTone(r.state)}>{nice(r.state)}</Tag></div></div></div>),...(!items.length?DEMO_ROWS.map(r=><div key={r[0]} className="listrow" onClick={()=>go('progress')} style={{cursor:'pointer'}}>{IconBox({n:catIcon(r[3].toLowerCase()),tone:r[3]==='Flood'?'blue':r[3]==='Wildlife'?'amber':''})}<div className="grow"><h3>{r[1]}</h3><p>{r[0]} · {r[2]}</p><div style={{marginTop:6}}><Tag tone={r[5]}>{r[4]}</Tag></div></div></div>):[])]}</Box><Btn wide onClick={()=>go('upload')}>Create another report</Btn><p className="small">Example data shown when the account has no reports yet.</p></>}

/* detail / progress */
function DetailScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Report EG-W-024" p="Wildlife sighting · Community A"/><Row between><Tag tone="amber">Under review</Tag><span className="small">Submitted 09:12</span></Row><Box><Row><img src="/assets/elephant.jpg" className="photo" style={{width:58,height:66}} alt="Evidence"/><div><h3>Possible elephant</h3><p>Identity suggestion not yet confirmed</p></div></Row><div className="line"></div><p>Seen near the field boundary. Submitted without approaching the animal.</p></Box><Box><h3>What happens next?</h3><div className="timeline"><div><strong>Report submitted</strong><p>Your evidence and consent were saved.</p></div><div><strong>Reviewer assigned</strong><p>The details are being checked.</p></div><div><strong>Decision and follow-up</strong><p>An outcome will appear here.</p></div></div></Box><Btn wide onClick={()=>go('messages')}>Add a clarification</Btn><Btn wide ghost onClick={()=>go('my-reports')}>Back to my reports</Btn></>}

/* community messages */
function MessagesScreen({go,toast}:{go:(p:string)=>void;toast:(m:string)=>void}){const [text,setText]=useState('');return <><MTitle t="Community messages" p="A clear record of questions and responses."/><Box><Row>{IconBox({n:'shield'})}<div><h3>Assigned reviewer</h3><p>Report EG-W-024</p></div><span style={{marginLeft:'auto'}}><Tag>Demo</Tag></span></Row></Box><div className="chatbubble">Thank you for your report. Was the animal inside the field or near the boundary?</div><div className="chatbubble me">Near the boundary. I stayed away and used an existing photo.</div><div className="chatbubble">Thank you. We will record that clarification and review the report.</div><Notice>Do not share exact wildlife locations in public messages.</Notice><div className="mfooter"><div className="field"><label>Reply to reviewer</label><input placeholder="Write a clarification..." value={text} onChange={e=>setText(e.target.value)}/></div><div style={{height:10}}></div><Btn wide onClick={()=>{toast('Demo reply only: no message was sent.');setText('');}}>Send example reply</Btn></div></>}

/* settings */
function SettingsScreen({go,user,toast}:{go:(p:string)=>void;user:User;toast:(m:string)=>void}){return <><MTitle t="Profile & preferences" p="Control your communities, language and privacy."/><Box><Row><span className="avatar large">{user.name.slice(0,1)}</span><div><h3>{user.name}</h3><p>Demonstration account</p></div></Row></Box><Field label="Preferred language"><select><option>English</option><option>Luganda (planned)</option><option>Other local language (planned)</option></select></Field><Field label="Followed communities"><input defaultValue="Community A, Community B"/></Field><Box className="card-list">{[['Wildlife alerts','Reviewed community advisories'],['Flood updates','Relevant information for your area'],['Protect my identity','Hide my name on public views']].map(([t,s])=><div key={t} className="listrow"><div className="grow"><h3>{t}</h3><p>{s}</p></div><button className="right toggle" onClick={(e)=>{e.currentTarget.classList.toggle('off');toast('Preference preview only.')}} aria-label={`Toggle ${t}`}></button></div>)}</Box><Btn wide onClick={()=>toast('Preferences changed in this demo only.')}>Save example preferences</Btn><Btn wide ghost onClick={()=>go('help')}>Help & privacy</Btn></>}

/* help */
function HelpScreen({go}:{go:(p:string)=>void}){return <><MTitle t="Help & safety" p="Useful guidance without false emergency promises."/><Box><Row>{IconBox({n:'shield',tone:'amber'})}<h3>Wildlife comes first</h3></Row><p style={{marginTop:10}}>Keep your distance. Do not approach an animal for a photograph or try to chase it away.</p></Box><Box><Row>{IconBox({n:'water',tone:'blue'})}<h3>Flood awareness</h3></Row><p style={{marginTop:10}}>Check the timestamp and source of an advisory. Follow official local guidance.</p></Box><Box><h3>Need a responder?</h3><p style={{marginTop:9}}>The pilot must configure verified local contacts. No emergency dispatch is connected in this demonstration.</p></Box><button type="button" className="pillbutton" onClick={()=>{}}><span>Privacy and data use</span><Icon n="chevron" s={15}/></button><button type="button" className="pillbutton" onClick={()=>go('messages')}><span>Ask about your report</span><Icon n="chevron" s={15}/></button><p className="small">For immediate danger, use established local emergency channels.</p></>}

/* =========================================================== DESKTOP APP */
const DSIDES:Array<[string,string,string]>= [['dashboard','home','Overview'],['wildlife','paw','Wildlife reports'],['verify','shield','Verification'],['map','map','Incident map'],['reports','file','All reports'],['wetland','leaf','Wetlands'],['flood','water','Flood information'],['alerts','bell','Alert centre'],['analytics','chart','Analytics'],['settings-admin','settings','Team & settings']];
function DesktopApp({user,route,go,onLogout}:{user:User;route:string;go:(p:string)=>void;onLogout:()=>void}){
 const {toast,node}=useToast();const tick=useRealtimeTick();const d=useData<Dashboard>('/dashboard',20000,tick);
 const name=route==='dashboard'?'Overview dashboard':route==='wildlife'?'Wildlife workspace':route==='verify'?'Verification workspace':route==='map'?'Incident map':route==='reports'?'Reports & cases':route==='wetland'?'Wetland workspace':route==='flood'?'Flood advisories':route==='alerts'?'Alert centre':route==='analytics'?'Analytics & export':'Team & settings';
 const awaiting=d.data?.counts.awaiting_review||0;
 return <div className="app-desktop desktop"><nav className="topnav"><Brand/><div className="navbarlinks"><button type="button" className={route==='dashboard'?'active':''} onClick={()=>go('dashboard')}>Workspace</button><button type="button" onClick={()=>go('home')}>Community</button><button type="button" onClick={()=>go('help')}>Resources</button></div><div className="search"><Icon n="search" s={15}/><input placeholder="Search reports, communities, cases..." aria-label="Search"/></div><div className="row"><Tag tone="gray">Live workspace</Tag><button type="button" style={{background:'none',color:'#577354'}} aria-label="Alerts" onClick={()=>go('alerts')}><Icon n="bell" s={20}/></button><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><span className="small">{user.name}</span></div></nav><div className="shell"><aside className="sidebar"><div className="eyebrow">PILOT WORKSPACE</div>{DSIDES.map(([k,i,l])=><button key={k} type="button" className={'sideitem '+(route===k?'active':'')} onClick={()=>go(k)}><Icon n={i} s={19}/><span>{l}</span>{k==='wildlife'&&<span className="badge">{String(awaiting||6).padStart(2,'0')}</span>}</button>)}<div className="sidehelp"><strong><Icon n="leaf" s={16}/> Application concept</strong><br/>Community-led reporting.<br/>No dedicated hardware.</div></aside><main className="workspace"><div className="workspace-inner"><PHead label={`ECOGUARD / ${name.toUpperCase()}`} title={name} sub="Wildlife-first community reporting and case coordination." action={<div className="row"><span className="small">{fmtDate()}</span><Btn small icon="plus" onClick={()=>go('upload')}>New report</Btn></div>}/>
   {route==='dashboard'&&<DashboardPage go={go} d={d}/>}
   {route==='wildlife'&&<WildlifePage go={go}/>}
   {route==='verify'&&<VerifyPage go={go}/>}
   {route==='map'&&<MapPage go={go}/>}
   {route==='reports'&&<ReportsPage go={go}/>}
   {route==='wetland'&&<WetlandPage go={go}/>}
   {route==='flood'&&<FloodPage go={go}/>}
   {route==='alerts'&&<AlertsPage go={go} toast={toast}/>}
   {route==='analytics'&&<AnalyticsPage go={go}/>}
   {route==='settings-admin'&&<SettingsPage go={go} user={user} toast={toast}/>}
  </div></main></div>{node}</div>;
}

/* desktop dashboard */
function DashboardPage({go,d}:{go:(p:string)=>void;d:ReturnType<typeof useData<Dashboard>>}){
 const tick=useRealtimeTick();const geo=d;const counts=d.data?.counts;const recent=d.data?.recent||[];const rows=recent.length?recent.slice(0,4).map(tRow):DEMO_ROWS.map(dRow);
 return <><DesktopHero go={go}/><div className="grid4 statrow"><Stat n={String(counts?.wildlife||12)} l="Wildlife reports" tone="amber"/><Stat n={String(counts?.wetland||8)} l="Wetland reports"/><Stat n={String(counts?.flood||4)} l="Flood updates" tone="blue"/><Stat n={String(counts?.awaiting_review||6)} l="Awaiting review"/></div><div className="overviewcards"><Box><Row between><h3>Reports needing attention</h3><LinkBtn onClick={()=>go('reports')}>View all <Icon n="chevron" s={12}/></LinkBtn></Row><table className="table"><thead><tr><th>Report</th><th>Area</th><th>Category</th><th>Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><strong>{r.title}</strong><br/>{r.demo&&<small>{r.code}</small>}</td><td>{r.area}</td><td>{r.cat}</td><td><Tag tone={r.tone}>{r.st}</Tag></td></tr>)}</tbody></table></Box><Box style={{padding:16}}><Row between style={{marginBottom:12}}><h3>Community overview</h3><Tag>Example</Tag></Row><SketchMap h={202}/></Box></div></>;
}

/* desktop wildlife */
function WildlifePage({go}:{go:(p:string)=>void}){const tick=useRealtimeTick();const d=useData<Collection<CaseReport>>('/reports?category=wildlife&page_size=12',20000,tick);const items=d.data?.items||[];return <><div className="subhero"><div><h2>Wildlife detection from submitted images</h2><p>AI suggests a species; an authorised reviewer decides. No connected camera feed.</p></div><Btn ghost icon="upload" onClick={()=>go('upload')}>Upload image</Btn></div><div className="subbar"><div className="tabrow"><button className="tab active">Awaiting review <b>06</b></button><button className="tab">Verified</button><button className="tab">Needs evidence</button><button className="tab">Closed</button></div><Btn ghost small icon="filter" onClick={()=>{}}>Filter</Btn></div><div className="gallery">{[...items.map((r,idx)=><article className="card detectcard" key={r.id}><div className="reviewimg"><img src={(r.evidence||[])[0]?.url||'/assets/elephant.jpg'} alt="Wildlife evidence"/>{idx!==1&&<div className="bounding"><b>Suggested region · Live</b></div>}</div><div className="info"><Row between><small>{r.code}</small><Tag tone={stateTone(r.state)}>{nice(r.state)}</Tag></Row><h3>{r.title}</h3><p>{r.area_name} · User-submitted example</p><div className="line"></div><p>Human verification required before publication.</p><div style={{height:12}}></div><Btn wide ghost onClick={()=>go('verify')}>Open review</Btn></div></article>),...(!items.length?[['EG-W-024','Possible elephant','Community A','elephant'],['EG-W-019','Unknown animal','Community C','wildlife'],['EG-W-018','Reported elephant','Community A','elephant']].map(([id,n,a,img],i)=><article className="card detectcard" key={id}><div className="reviewimg"><img src={`/assets/${img==='wildlife'?'landscape':img}.jpg`} alt="Wildlife evidence"/>{i!==1&&<div className="bounding"><b>Suggested region · Demo</b></div>}</div><div className="info"><Row between><small>{id}</small><Tag tone="amber">{i===1?'Needs evidence':'Under review'}</Tag></Row><h3>{n}</h3><p>{a} · User-submitted example</p><div className="line"></div><p>Human verification required before publication.</p><div style={{height:12}}></div><Btn wide ghost onClick={()=>go('verify')}>Open review</Btn></div></article>):[])]}</div><div style={{height:16}}></div><Notice tone="amber">Demonstration suggestions are not model accuracy results. Local labelled data and independent evaluation are required.</Notice></>}

/* desktop verify */
function VerifyPage({go}:{go:(p:string)=>void}){return <><div className="grid2" style={{gridTemplateColumns:'1.25fr 1fr'}}><Box><Row between style={{marginBottom:13}}><h3>Image and observation</h3><Tag>EG-W-024</Tag></Row><div className="reviewimg" style={{height:269}}><img src="/assets/elephant.jpg" alt="Wildlife evidence"/><div className="bounding"><b>Possible elephant · Example</b></div></div><div className="grid2" style={{marginTop:16}}><div><small>APPROXIMATE AREA</small><p>Community A</p></div><div><small>REPORT TIME</small><p>20 Sep 2026 · 09:12</p></div></div><div className="line"></div><p style={{fontSize:14}}>“Seen near the field boundary. No approach made.”</p><p className="small" style={{marginTop:8}}>Precise location and reporter contact: restricted access.</p></Box><Box className="stack"><Row between><h3>Reviewer decision</h3><Tag tone="amber">Human review</Tag></Row><Field label="Species / category"><select><option>Possible elephant</option><option>Unknown animal</option><option>Other</option></select></Field><Field label="Evidence assessment"><select><option>Further review required</option><option>Verified report</option><option>Insufficient evidence</option></select></Field><Field label="Reviewer notes"><textarea defaultValue="Check the original image, timestamp and approximate area before deciding."/></Field><CheckRow checked>Do not reveal precise wildlife coordinates to the public.</CheckRow><div className="grid2"><Btn ghost onClick={()=>{}}>Request clarification</Btn><Btn onClick={()=>{}}>Save review</Btn></div><Btn wide ghost onClick={()=>go('alerts')}>Prepare reviewed advisory</Btn><Notice>AI output is supporting evidence, not the final decision.</Notice></Box></div></>}

/* desktop map */
function MapPage({go}:{go:(p:string)=>void}){return <><div className="subbar"><div className="tabrow"><button className="tab active">All reports</button><button className="tab">Wildlife</button><button className="tab">Wetland</button><button className="tab">Flood</button></div><Row><Tag tone="gray">Locations generalised</Tag><Btn ghost small icon="filter" onClick={()=>{}}>Filters</Btn></Row></div><div className="grid2" style={{gridTemplateColumns:'2fr 1fr'}}><Box style={{padding:13}}><SketchMap h={491}/></Box><div className="stack"><Box><Row>{IconBox({n:'paw',tone:'amber'})}<div><h3>Report EG-W-024</h3><p className="small">Community A</p></div></Row><div className="line"></div><Tag tone="amber">Under review</Tag><p style={{fontSize:13,margin:'15px 0'}}>Possible elephant reported near a field boundary. Exact location is restricted.</p><Btn wide onClick={()=>go('verify')}>Review this report</Btn></Box><Box><h3>Map legend</h3><div className="listrow">{IconBox({n:'paw',tone:'amber'})} Wildlife reports</div><div className="listrow">{IconBox({n:'leaf'})} Wetland reports</div><div className="listrow">{IconBox({n:'water',tone:'blue'})} Flood information</div></Box><Notice tone="blue">This illustrative map is not suitable for navigation.</Notice></div></div></>}

/* desktop reports */
function ReportsPage({go}:{go:(p:string)=>void}){const tick=useRealtimeTick();const d=useData<Collection<CaseReport>>('/reports?page_size=50',20000,tick);const items=d.data?.items||[];const rows=items.length?items.map(tRow):DEMO_ROWS.map(dRow);return <><div className="grid4 statrow"><Stat n={String(items.length||24)} l="Total examples"/><Stat n={String(items.filter(r=>['submitted','under_review','needs_evidence'].includes(r.state)).length||6)} l="Pending review" tone="amber"/><Stat n={String(items.filter(r=>['verified','published','closed'].includes(r.state)).length||11)} l="Reviewed"/><Stat n={String(items.filter(r=>r.state==='closed').length||7)} l="Closed cases"/></div><Box><div className="subbar"><div className="tabrow"><button className="tab active">All cases</button><button className="tab">Assigned to me</button><button className="tab">Needs follow-up</button></div><Btn ghost small icon="download" onClick={()=>downloadExport().catch(()=>{})}>Export example</Btn></div><table className="table"><thead><tr><th>Report</th><th>Area</th><th>Category</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><strong>{r.title}</strong><br/><small>{r.code}</small></td><td>{r.area}</td><td>{r.cat}</td><td><Tag tone={r.tone}>{r.st}</Tag></td><td><LinkBtn onClick={()=>go('verify')}>Review <Icon n="chevron" s={12}/></LinkBtn></td></tr>)}</tbody></table><Row between style={{marginTop:15}}><span className="small">Showing {Math.max(items.length,4)} example cases</span><div className="tabrow"><button className="tab active">1</button><button className="tab">2</button></div></Row></Box><div style={{height:18}}></div><div className="grid2"><div className="callout"><strong>A shared case record</strong><br/>Each report retains evidence, reviewer notes, notification attempts and follow-up actions.</div><div className="callout"><strong>Role-based access</strong><br/>Community users see their own reports; reviewers work only within authorised areas.</div></div></>}

/* desktop wetland */
function WetlandPage({go}:{go:(p:string)=>void}){return <><div className="subhero"><div><h2>Turn wetland observations into case follow-up</h2><p>Review community evidence and record the action taken by the assigned officer.</p></div><Tag tone="gray">Observation ≠ confirmed offence</Tag></div><div className="grid2" style={{gridTemplateColumns:'1.15fr 1fr'}}><Box><Row between style={{marginBottom:14}}><h3>Report EG-E-011</h3><Tag>Assigned</Tag></Row><img className="photo" src="/assets/wetland.jpg" style={{height:245}} alt="Wetland evidence"/><p style={{fontSize:14,margin:'15px 0'}}>Possible construction activity near a wetland edge.</p><div className="grid2"><div><small>AREA</small><p>Wetland zone A</p></div><div><small>REPORT SOURCE</small><p>Community upload</p></div></div></Box><Box className="stack"><h3>Case action</h3><Field label="Concern type"><select><option>Possible encroachment</option><option>Dumping</option><option>Draining</option></select></Field><Field label="Assign reviewer"><select><option>Environment officer A</option><option>Environment officer B</option></select></Field><Field label="Next step"><textarea defaultValue="Review the submission and request additional context through the community contact channel."/></Field><Btn wide onClick={()=>{}}>Save follow-up action</Btn><Notice>No enforcement claim is made until an authorised officer has assessed the report.</Notice></Box></div></>}

/* desktop flood */
function FloodPage({go}:{go:(p:string)=>void}){return <><div className="subhero" style={{background:'#e9f3f6',borderColor:'#d6e6ec'}}><div><h2>Reviewed flood information, not a sensor dashboard</h2><p>Bring community observations and attributed external advisories together.</p></div><Tag tone="blue">Information source required</Tag></div><div className="grid2" style={{gridTemplateColumns:'1.3fr 1fr'}}><div className="stack"><Box><Row between><h3>Community water reports</h3><Tag tone="blue">04 examples</Tag></Row><table className="table"><thead><tr><th>Area</th><th>Observation</th><th>Status</th></tr></thead><tbody><tr><td>Community B</td><td>Water reported rising</td><td><Tag tone="blue">Under review</Tag></td></tr><tr><td>Community D</td><td>Road flooding reported</td><td><Tag tone="amber">Needs evidence</Tag></td></tr><tr><td>Community A</td><td>Water has receded</td><td><Tag>Reviewed</Tag></td></tr></tbody></table></Box><Box><h3>External advisory source</h3><div className="line"></div><Row between><div><strong style={{fontSize:14}}>Official feed integration</strong><p className="small">Provider selection is part of the pilot.</p></div><Tag tone="gray">Not connected</Tag></Row><p style={{fontSize:13,marginTop:15}}>Display the source, issue time, affected area and expiry time before publishing an update.</p></Box></div><Box className="stack"><img className="photo" src="/assets/flood.jpg" style={{height:193}} alt="Flood illustration"/><h3>Create an information update</h3><p className="small">Example only. This image does not establish current flooding.</p><Field label="Affected community"><select><option>Community B</option><option>Community D</option></select></Field><Btn wide onClick={()=>go('alerts')}>Prepare advisory</Btn><Notice tone="blue">Do not claim a guaranteed flood prediction or warning lead time.</Notice></Box></div></>}

/* desktop alerts */
function AlertsPage({go,toast}:{go:(p:string)=>void;toast:(m:string)=>void}){const d=useData<Collection<Advisory>>('/advisories?staff=true',20000);const a=d.data?.items?.[0];return <><div className="grid2" style={{gridTemplateColumns:'1.25fr 1fr'}}><Box className="stack"><Row between><h3>Compose a reviewed advisory</h3><Tag tone="amber">Draft</Tag></Row><div className="grid2"><Field label="Category"><select><option>Wildlife advisory</option><option>Flood information</option><option>Wetland update</option></select></Field><Field label="Target community"><select><option>Community A</option><option>Community B</option></select></Field></div><Field label="Title"><input defaultValue="Wildlife advisory for Community A"/></Field><Field label="Message"><textarea style={{height:100}} defaultValue="A reviewed wildlife sighting is shared for awareness. Keep your distance and follow local responder guidance. The location is generalised."/></Field><div className="row"><Tag>In-app</Tag><Tag tone="gray">SMS · optional</Tag><Tag tone="gray">WhatsApp · optional</Tag></div><CheckRow checked>I have verified the report and removed exact wildlife locations from this public message.</CheckRow><div className="grid2"><Btn ghost onClick={()=>toast('Draft saved locally in this prototype.')}>Save draft</Btn><Btn onClick={()=>toast('This prototype does not publish or send real alerts.')}>Preview advisory</Btn></div><Notice>Only authorised reviewers may publish. Channel delivery is not guaranteed.</Notice></Box><div className="stack"><Box><h3>Community preview</h3><div className="line"></div><div className={'notice amber'}><strong>{(a&&a.title)||'Wildlife advisory'}</strong><p style={{marginTop:8,fontSize:13}}>{(a&&a.area_name)||'Community A'} · Reviewed example</p><p style={{marginTop:9,fontSize:13}}>{(a&&a.body)||'Keep your distance. Read the full advisory before acting.'}</p></div><p className="small" style={{marginTop:14}}>Source report: EG-W-024<br/>Identity hidden · Location generalised</p></Box><Box><h3>Publication checklist</h3><div className="listrow"><Icon n="check" s={17}/> Human verification complete</div><div className="listrow"><Icon n="check" s={17}/> Audience and time window set</div><div className="listrow"><Icon n="check" s={17}/> Sensitive details removed</div><div className="listrow"><Icon n="clock" s={17}/> Channel status checked</div></Box></div></div></>}

/* desktop analytics */
function AnalChart(){return <svg className="chart" viewBox="0 0 590 170"><path d="M32 15H580M32 50H580M32 85H580M32 120H580" stroke="#e2eadb" fill="none"/><path d="M32 113 90 94 147 106 202 66 260 80 317 58 374 64 430 26 488 47 546 25 580 36 580 120 32 120Z" fill="#e3eed5"/><path d="M32 113 90 94 147 106 202 66 260 80 317 58 374 64 430 26 488 47 546 25 580 36" stroke="#477646" strokeWidth="3" fill="none"/><path d="M32 116 90 112 147 100 202 106 260 95 317 110 374 78 430 92 488 77 546 89 580 71" stroke="#6b9faf" strokeWidth="2.5" fill="none"/><g fontFamily="Arial" fontSize="10" fill="#71836d"><text x="31" y="143">Week 1</text><text x="202" y="143">Week 2</text><text x="373" y="143">Week 3</text><text x="531" y="143">Week 4</text></g></svg>}
function AnalyticsPage({go}:{go:(p:string)=>void}){const tick=useRealtimeTick();const d=useData<Dashboard>('/dashboard',20000,tick);const c=d.data?.counts||{};const total=c.total||24;const w=c.wildlife||12,e=c.wetland||8,f=c.flood||4;const wPct=total?Math.round(w/total*100):50,ePct=total?Math.round((w+e)/total*100):78;return <><div className="grid4 statrow"><Stat n={String(total)} l="Total reports"/><Stat n={String(c.verified||11)} l="Reviewed reports"/><Stat n={String(c.closed||7)} l="Closed cases"/><Stat n={String(c.awaiting_review||3)} l="Advisory drafts" tone="amber"/></div><div className="grid2" style={{gridTemplateColumns:'1.5fr 1fr'}}><Box><Row between><h3>Reporting activity</h3><Tag>Illustrative values</Tag></Row><AnalChart/><div className="row small"><span><i className="dot"></i>Wildlife / wetland reports</span><span><i className="dot" style={{background:'#6b9faf'}}></i>Flood information</span></div></Box><Box><h3>Report mix</h3><div className="row" style={{justifyContent:'space-around',marginTop:19}}><div className="donut"><div><strong>{total}</strong><small>examples</small></div></div><div className="stack small"><span><i className="dot" style={{background:'#2d754d'}}></i>Wildlife</span><span><i className="dot" style={{background:'#96b86e'}}></i>Wetland</span><span><i className="dot" style={{background:'#75a7b1'}}></i>Flood</span></div></div></Box></div><div style={{height:18}}></div><Box><Row between><div><h3>Pilot evaluation export</h3><p className="small" style={{marginTop:5}}>Time to submit · Review turnaround · Identification errors · Alert delivery</p></div><Btn ghost small icon="download" onClick={()=>downloadExport().catch(()=>{})}>Export sample CSV</Btn></Row><div className="line"></div><div className="grid3"><div><small>DATA QUALITY</small><p style={{fontSize:14}}>Completeness and duplicate cases</p></div><div><small>AI EVALUATION</small><p style={{fontSize:14}}>Species-level precision and recall</p></div><div><small>USER EXPERIENCE</small><p style={{fontSize:14}}>Task completion and usability</p></div></div></Box></>}

/* desktop settings */
function SettingsPage({go,user,toast}:{go:(p:string)=>void;user:User;toast:(m:string)=>void}){return <><div className="tabrow" style={{marginBottom:18}}><button className="tab active">Team & access</button><button className="tab">Privacy</button><button className="tab">Integrations</button><button className="tab">Audit history</button></div><div className="grid2" style={{gridTemplateColumns:'1.4fr 1fr'}}><Box><Row between><h3>Workspace team</h3><Btn small icon="plus" onClick={()=>toast('No invitation is sent from this prototype.')}>Invite reviewer</Btn></Row><table className="table"><thead><tr><th>Member</th><th>Role</th><th>Area</th></tr></thead><tbody><tr><td><div className="row"><span className="avatar">RA</span><strong>Reviewer A</strong></div></td><td>Wildlife reviewer</td><td>Community A</td></tr><tr><td><div className="row"><span className="avatar">EO</span><strong>Officer B</strong></div></td><td>Environment officer</td><td>Wetland zone A</td></tr><tr><td><div className="row"><span className="avatar">AD</span><strong>Admin C</strong></div></td><td>Workspace admin</td><td>All pilot areas</td></tr></tbody></table><div className="line"></div><h3>Community access</h3><p className="small" style={{margin:'10px 0'}}>Community users submit reports and view approved, generalised advisories. They cannot view private evidence or change reviewer decisions.</p></Box><div className="stack"><Box><h3>Default safeguards</h3>{[['Hide reporter identities',true],['Generalise wildlife locations',true],['Require human verification',true],['Auto-publish AI results',false]].map(([t,on])=><ToggleRow key={t as string} label={<span style={{fontSize:13}}>{t}</span>} on={!!on} onClick={()=>toast('Safety settings are fixed in this demonstration.')}/>)}</Box><Box><h3>Integrations</h3><div className="listrow"><span style={{fontSize:13}}>AI model endpoint</span><span style={{marginLeft:'auto'}}><Tag tone="gray">Not connected</Tag></span></div><div className="listrow"><span style={{fontSize:13}}>SMS gateway</span><span style={{marginLeft:'auto'}}><Tag tone="gray">Optional</Tag></span></div><div className="listrow"><span style={{fontSize:13}}>External advisories</span><span style={{marginLeft:'auto'}}><Tag tone="gray">Not connected</Tag></span></div></Box><Box><h3>Workspace admin</h3><p className="small" style={{marginBottom:10}}>Signed in as <strong>{user.email}</strong>.</p><Btn type="button" red ghost onClick={()=>toast('Use the sidebar to review reports and cases first.')}>Review metrics</Btn></Box></div></div></>}